### PR TITLE
Updated PSR4 class locator to add a namespace index

### PR DESCRIPTION
**Pull request by oligriffiths**
Additionally removed the underscore split as this isn't part of the PSR 4 spec

### CODE REVIEW

**Comment by johanjanssens** [comment]
@oligriffiths Can you explain this PR in more detail please ?

**Comment by oligriffiths** [comment]
Sure. So the way the composer PSR4 loader works, is by indexing the namespaces by the first character of the namespace, so that the majority of namespaces can be eliminated to begin with. Then it stores the length of the namespace so that can be re-used when iterating namespaces to try and match against the class being loaded and make the namespace matching more efficient.

**Comment by johanjanssens** [comment]
This lookup mechanism could also be potentially beneficial for our own loaders, if I understand it correctly ?

**Comment by oligriffiths** [comment]
Yup, I actually had a separate PR for the class loader to do just this, but you have to invert where the namespaces are stored, making the class loader the authority rather than the loaders themselves. That also reduces the need for the loaders to iterate over their registered namespaces. It's a bigger refactor so you might not wanna do that now.

**Comment by johanjanssens** [comment]
I saw that. I'll start with this optimisation, can apply it to the abstract loader I think. Will research in more detail.

**Comment by oligriffiths** [comment]
Yeah, that's what my PR did. Would make the loaders themselves simpler and more efficient.

**Comment by johanjanssens** [comment]
@oligriffiths Looked into this. Don't see the need for this optimisation. The PSR loader in Kodekit is only added in the case that Composer is not available and vendor libraries that follow PSR need to be loaded. Scenario's like when including a library with your own component. In that scenario that optimisation you propose is not needed. I could add it, but then it would be specific to the PSR locator as I cannot add the same optimisation for all locators, it would also not have much effect there.

**Pull request closed without merging**
