### PR TITLE
Lazy load class registry & allow config to be changed post instantiation

### PR DESCRIPTION
**Pull request by oligriffiths**
So here's the problem.

`Nooku\Library\ClassLoader::getInstance($config)` must be called with the config before any use of the loader. This produces a race condition with composer packages that need to register a namespace for a loader:

```php
Nooku\Library\ClassLoader::getInstance()->getLocator('library')->registerNamespace(
    'Nooku\\Library', dirname(__FILE__).'/lib'
);
```

This causes the class loader to be initialized with no config. Due to the way that composer includes files in the autoload cycle, autoload files for packages are called as part of the `require vendor/autoload.php`. If the class loader is also a composer package, there is no way to configure the loader prior to be being used by other packages. For example, the include path goes as follows:

* include vendor/autoload.php
* loop autoload files for packages
* include class loader
* include other package that requires class loader and calls `Nooku\Library\ClassLoader::getInstance()->getLocator()->registerNamespace()`
* class locator instantiated
* now can't set caching on loader :(

This patch allows caching to be enabled prior to any use of the registry.

### CODE REVIEW

**Comment by oligriffiths** [comment]
Also, sorry for making more work :s

**Comment by oligriffiths** [comment]
Bump

**Comment by johanjanssens** [comment]
@oligriffiths The problem with the namespace registrations has now been solved. This is happening during bootstrapping. Namespaces are defined for each package in the component.json file. See : https://github.com/timble/kodekit-platform/blob/master/application/admin/component/activities/component.json

For registering other custom namespaces to the loader think one should consider the fact if the ClassLoader should actually be a singleton on it's own. The less singletons the better.

Might actually be better if the Kodekit object keeps and exposes the loader. It could expose the object manager in a same way. 

If you follow that idea, then you can ask who should store a reference to the classloader, the kodekit object or the object manager itself.

**Comment by johanjanssens** [comment]
@oligriffiths Closing this issue. Created a new issue to work on a couple of points you mentioned. You can follow progress here : timble/kodekit#34

**Pull request closed without merging**
