### PR TITLE
Added thumbnail_size support to attachable behavior & EntityAttachment

### PR DESCRIPTION
**Pull request by oligriffiths**
Implemented the ability to define the thumbnail size of attachments when using the attachable behavior

### CODE REVIEW

**Comment by tomjanssens** [comment]
Suggest to rename `thumbnail_size` to `thumbnail_ratio` since the setting describes the proportional relationship between width and height.

**Comment by oligriffiths** [comment]
well, it's not just ratio, it covers size, which in turn defines a ratio.

**Comment by tomjanssens** [comment]
Cool, you are right! Just figured out you can also do something like:
`$thumbnail->setThumbnailSize(array('x' => 150, 'y' => 150))->generateThumbnail()->save($this->thumbnail_fullpath)`

However, we have another issue, the ratio is also hardcoded in https://github.com/nooku/nooku-platform/blob/develop/component/attachments/resources/assets/js/attachments.list.js#L52

**Comment by oligriffiths** [comment]
Hmm, ok. I've only been working with it from a server side perspective. We could pass the thumb size as a parameter to the JS if we can pull that data from the controller behaviour, not sure if this is possible. 

@johanjanssens thoughts?

**Comment by oligriffiths** [comment]
Also, as the default size matches the JS, this PR can be merged without introducing a BC break.

**Comment by johanjanssens** [comment]
@oligriffiths @tomjanssens  Don't know enough about the cropping implementation but to me it seems the thumbnail generation and the client side cropping are two different things. The client side implementation is actually overlaying the server side implementation. Not sure we need to worry here about the client side as the parameter @oligriffiths is suggesting involves the attachable behaviour only ?

**Comment by oligriffiths** [comment]
Agreed. The server side part has nothing to do with the client, an API for example has not html client to speak of. I'd favour keeping these separate, perhaps having the client side read the settings of the sever side piece.

**Pull request closed without merging**
